server:
  port: 8082

spring:
  application:
    name: movie-service

  datasource:
    url: jdbc:mysql://localhost:3306/movie_db
    username: root
    password: yash

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/